server:
  port: 9000

spring:
  application:
    name: auth_service
  datasource:
    url: jdbc:postgresql://localhost:5434/auth
    username: auth
    password: auth
    driver-class-name: org.postgresql.Driver

  flyway:
    enable: true
